# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
joel = User.create(first_name: "Joel", last_name: "Langstein", email: "joellangstein@gmail.com", about_text: "coming soon")
Post.create(title: "While the NFL dropped the ball; Ray Rice is still to blame", post_text: "The NFL has been under a lot of scrutiny the past few weeks regarding their mishandling of the Ray Rice domestic abuse situation.  It seems as if the focus is more on the NFL and what they didn't do, as opposed to what Ray Rice shouldn't have done.  Although Ray Rice has been punished, some of the focus is being taken off of him and being put on the NFL and how they were ignorant about Rice's assault at an Atlantic City casino. \n\n\nIf Ray Rice didn't hit his then fiancee and now wife, the NFL never would have been put in the position they are now.  I am not excusing Roger Goodell's actions, because his ignorance of not being on top of things from the get go is arguably a fireable offense.  However, the main blame should be put on the players who commit these terrible acts of violence.  The NFL and its players are being villainized for things that a few individual players did.  Domestic abuse is not an NFL problem, but rather, a societal problem.  It is just being magnified through NFL players because of their fame and public stature.  Yes, these players are held to a higher standard then the normal citizen, but the amount of well-behaved players in the NFL outweighs the number of poor behaved players. \n\nI am no fan of Roger Goodell and the lack of support for him by the players shows that they know what is right and what is wrong.  Although Goodell says he has support from the owners, that is only 32 people.  He is hated by many players and does not look good in the public eye.  That is why, when looking at the Ray Rice fiasco, the situation should be compartmentalized.  The entire NFL is not a corrupt business that condones crime and only cares about the money.  While there are definitely some inside the league office that turn a blind eye, they do not represent the feelings of the majority of the NFL employees. \n\nRoger Goodell deserved to be grilled on national television yesterday by reporters, but why don't we see Ray Rice at the microphone?  He should be grilled by the public as well.  He should have to answer why he punched his wife in the face and how is he going to live with himself knowing that he committed a terrible act of violence.  The NFL may want to protect the shield and have things kept hidden, and that is not acceptable.  But it all starts with Ray Rice.  If he didn't knock out a woman in an elevator.  These discussions would never have taken place.", user: joel, created_at: Chronic.parse('September 20'))
Post.create(title: 'The Jets and the Giants come up short yet again', post_text: "Aweful. That just about sums it up for the performances put on by the Jets and the Giants earlier today. Whether it was the horrific fumble by Rashad Jennings of the Giants, or the unfathomable nullifying timeout that cost the Jets a tying touchdown in Green Bay, there is nothing positive to talk about. Unfortunately, there are no moral victories in football. Therefore, there are no silver linings to discuss. While the Giants had a more fluid offense, they lost to a backup quarterback in Drew Stanton, an inexcusable act. For the Jets, blowing a 21-3 lead against an elite team on the road may turn into a season altering loss. \n\nTom Coughlin and Rex Ryan are usually regarded as player-friendly coaches in NFL circles, but the mistakes made by both teams today reflect poorly on both coaches. The poor special teams play by the Giants reflects a lack of discipline instilled by Tom Coughlin. Similarly for Gang Green, the complete loss of composure in the second half by Muhammed Wilkerson reflects on Rex's poor discipline of his team. These coaches may be loved by their players, but who cares? If the team is not performing, does it really matter if the players like the coach? A team that wins and doesn't love their coach is more ideal than having a team with players that are inseparable with their coach but lose. \n\nFrom afar, it appears that the Jets and Giants are both in for long campaigns this season. No game on the schedule is a guaranteed win for the Giants anymore, and the Jets will be lucky to win one of the next five games they play. After all the preseason hype, it is beginning to look like there will be no New York football team playing in January. These two teams have constantly failed to answer the bell the last couple of years, and the excuses are getting old.", user: joel, created_at: Chronic.parse('September 14'))
